import { Inter } from "next/font/google";
import "./globals.css";
import "./OtherStyle.css";
import { NavBar, Footer } from "./components";
import { StateContext } from "./context/StateContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bag Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StateContext>
          <NavBar />
          <main>{children}</main>
          <Footer />
        </StateContext>
      </body>
    </html>
  );
}
